# Generated by Django 3.2.4 on 2021-06-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price_level',
            field=models.CharField(choices=[('1', '$'), ('2', '$$'), ('3', '$$$')], default='1', max_length=10),
        ),
    ]
